name: Nirmal Mehta's blog
title: Nirmal's blog
description: Posts from Nirmal Mehta
incremental: true

links:
  dribbble:
  email:
  facebook:
  flickr:
  github: normalfaults
  instagram: nirmal.io
  linkedin: nirmalkmehta
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: normalfaults
  stackoverflow:
  youtube:
  googleplus:
  github: normalfaults
  keybase: nirmal
github_username: normalfaults
twitter_username: normalfaults

theme: jekyll-theme-slate

google_analytics: UA-148077309-1

url: "http://nirmal.io"

baseurl: ""

permalink: /:year/:month/:title/
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
